# Generated by Django 3.0.5 on 2020-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact_Info', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='')),
                ('Desc', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfDisaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Desc', models.TextField(max_length=2048)),
                ('Image', models.ImageField(upload_to='')),
                ('GettingHelp', models.CharField(max_length=300)),
                ('Risk', models.CharField(max_length=300)),
            ],
        ),
    ]
