# Generated by Django 3.0.5 on 2020-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='')),
                ('Desc', models.TextField(max_length=2048)),
                ('Date', models.DateField()),
            ],
        ),
    ]
