# Generated by Django 3.0.5 on 2020-05-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
