# Generated by Django 3.0.5 on 2020-05-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20200527_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Conpass',
        ),
    ]
