# Generated by Django 3.0.5 on 2020-06-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpsupport',
            name='Subject',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='notify',
            name='Subject',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='Subject',
            field=models.CharField(max_length=300),
        ),
    ]
