# Generated by Django 3.0.5 on 2020-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_auto_20200609_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='Date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
