# Generated by Django 3.0.5 on 2020-06-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_notify_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notify',
        ),
    ]
